AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for building the infrastructure to implement a lambda function HTML Validator.

Resources:
  HTMLValidatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 60
      Layers:
        - !Ref DependenciesLayers

      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /testurl
            Method: get

  DependenciesLayers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Dependencies-layer
      Description: Python dependencies needed to run the lambda function code
      ContentUri: package/
      CompatibleRuntimes:
        - python3.8

  HttpValidatorApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Tags:
        Tag: Value
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      StageVariables:
        StageVar: Value
      FailOnWarnings: true


Outputs:
  LambdaApi:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod/'
  HttpApiId:
    Description: Api id of HttpValidatorApi
    Value:
      Ref: HttpValidatorApi
  LambdaFunction:
    Description: "HTML Validator Lambda Function"
    Value: !GetAtt HTMLValidatorFunction.Arn